<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $hotDrinks = Category::where('slug', 'hot-drinks')->first();
        $coldDrinks = Category::where('slug', 'cold-drinks')->first();
        $desserts = Category::where('slug', 'desserts')->first();
        $pastries = Category::where('slug', 'pastries')->first();
        $breakfast = Category::where('slug', 'breakfast')->first();

        $products = [
            // Hot Drinks
            [
                'title' => 'اسپرسو',
                'slug' => 'espresso',
                'price' => 150000,
                'category_id' => $hotDrinks->id,
                'description' => 'اسپرسو ایتالیایی با عطر و طعم بی‌نظیر. تهیه شده از بهترین دانه‌های قهوه عربیکا.',
                'image' => 'https://images.unsplash.com/photo-1510707577719-ae7c14805e3a?w=400&h=300&fit=crop',
                'rating' => 4.8,
                'inventory' => 100,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'آمریکانو',
                'slug' => 'americano',
                'price' => 170000,
                'category_id' => $hotDrinks->id,
                'description' => 'آمریکانو کلاسیک با طعم ملایم و دلپذیر. مناسب برای کسانی که قهوه تلخ دوست دارند.',
                'image' => 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=400&h=300&fit=crop',
                'rating' => 4.6,
                'inventory' => 100,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'کاپوچینو',
                'slug' => 'cappuccino',
                'price' => 200000,
                'category_id' => $hotDrinks->id,
                'description' => 'کاپوچینو اصیل با فوم شیر نرم و خامه‌ای. ترکیب عالی قهوه و شیر.',
                'image' => 'https://images.unsplash.com/photo-1572442388796-11668a67e53d?w=400&h=300&fit=crop',
                'rating' => 4.9,
                'inventory' => 80,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'title' => 'لاته',
                'slug' => 'latte',
                'price' => 210000,
                'category_id' => $hotDrinks->id,
                'description' => 'لاته کرمی با لایه نازک فوم شیر و عطر قهوه. نوشیدنی محبوب قهوه‌دوستان.',
                'image' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop',
                'rating' => 4.7,
                'inventory' => 80,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'title' => 'موکا',
                'slug' => 'mocha',
                'price' => 230000,
                'category_id' => $hotDrinks->id,
                'description' => 'موکا شکلاتی با ترکیب قهوه اسپرسو، شکلات داغ و شیر بخار. برای علاقه‌مندان به شکلات.',
                'image' => 'https://images.unsplash.com/photo-1578314675249-a6910f80cc4e?w=400&h=300&fit=crop',
                'rating' => 4.8,
                'inventory' => 70,
                'is_active' => true,
                'sort_order' => 5,
            ],

            // Cold Drinks
            [
                'title' => 'آیس کافی',
                'slug' => 'iced-coffee',
                'price' => 190000,
                'category_id' => $coldDrinks->id,
                'description' => 'قهوه سرد با یخ و شیر. نوشیدنی تازه‌کننده برای روزهای گرم تابستان.',
                'image' => 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=400&h=300&fit=crop',
                'rating' => 4.5,
                'inventory' => 90,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'موکا فریز',
                'slug' => 'mocha-frappe',
                'price' => 250000,
                'category_id' => $coldDrinks->id,
                'description' => 'موکا فریز یخی با شکلات و خامه. ترکیب خنک و شیرین برای گرمازدگان.',
                'image' => 'https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=300&fit=crop',
                'rating' => 4.7,
                'inventory' => 60,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'اسموتی توت‌فرنگی',
                'slug' => 'strawberry-smoothie',
                'price' => 220000,
                'category_id' => $coldDrinks->id,
                'description' => 'اسموتی تازه توت‌فرنگی با ماست یونانی و عسل. سرشار از ویتامین.',
                'image' => 'https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=400&h=300&fit=crop',
                'rating' => 4.6,
                'inventory' => 50,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'title' => 'چای سرد هلو',
                'slug' => 'peach-iced-tea',
                'price' => 180000,
                'category_id' => $coldDrinks->id,
                'description' => 'چای سرد با طعم هلو طبیعی و نعناع تازه. نوشیدنی گیاهی و سالم.',
                'image' => 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=300&fit=crop',
                'rating' => 4.4,
                'inventory' => 70,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'title' => 'لیموناد زعفرانی',
                'slug' => 'saffron-lemonade',
                'price' => 160000,
                'category_id' => $coldDrinks->id,
                'description' => 'لیموناد سنتی با زعفران اصل ایرانی و گلاب. طعمی منحصربه‌فرد.',
                'image' => 'https://images.unsplash.com/photo-1621263764928-df1444c5e953?w=400&h=300&fit=crop',
                'rating' => 4.8,
                'inventory' => 80,
                'is_active' => true,
                'sort_order' => 5,
            ],

            // Desserts
            [
                'title' => 'کیک شکلاتی',
                'slug' => 'chocolate-cake',
                'price' => 280000,
                'category_id' => $desserts->id,
                'description' => 'کیک شکلاتی تازه با روکش گاناش شکلات تلخ. رویای شکلات‌دوستان.',
                'image' => 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=400&h=300&fit=crop',
                'rating' => 4.9,
                'inventory' => 30,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'چیزکیک',
                'slug' => 'cheesecake',
                'price' => 300000,
                'category_id' => $desserts->id,
                'description' => 'چیزکیک نیویورکی با پایه بیسکوییت و مغز پنیر خامه‌ای. دسر کلاسیک و محبوب.',
                'image' => 'https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=400&h=300&fit=crop',
                'rating' => 4.8,
                'inventory' => 25,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'تیرامیسو',
                'slug' => 'tiramisu',
                'price' => 320000,
                'category_id' => $desserts->id,
                'description' => 'تیرامیسو اصیل ایتالیایی با قهوه اسپرسو و ماسکارپونه. دسری لطیف و عالی.',
                'image' => 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop',
                'rating' => 4.7,
                'inventory' => 20,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'title' => 'بستنی وانیلی',
                'slug' => 'vanilla-icecream',
                'price' => 150000,
                'category_id' => $desserts->id,
                'description' => 'بستنی وانیلی دست‌ساز با وانیل طبیعی. کرمی و خوشمزه.',
                'image' => 'https://images.unsplash.com/photo-1497034825429-c343d7c6a68f?w=400&h=300&fit=crop',
                'rating' => 4.5,
                'inventory' => 40,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'title' => 'پودینگ شکلاتی',
                'slug' => 'chocolate-pudding',
                'price' => 180000,
                'category_id' => $desserts->id,
                'description' => 'پودینگ شکلاتی غلیظ با خامه و دانه‌های کاکائو. برای علاقه‌مندان به شکلات.',
                'image' => 'https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?w=400&h=300&fit=crop',
                'rating' => 4.6,
                'inventory' => 35,
                'is_active' => true,
                'sort_order' => 5,
            ],

            // Pastries
            [
                'title' => 'کروسان',
                'slug' => 'croissant',
                'price' => 120000,
                'category_id' => $pastries->id,
                'description' => 'کروسان تازه و پر از کره فرانسوی. لایه‌های نازک و طلایی با طعم بی‌نظیر.',
                'image' => 'https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=400&h=300&fit=crop',
                'rating' => 4.8,
                'inventory' => 50,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'مافین بلوبری',
                'slug' => 'blueberry-muffin',
                'price' => 130000,
                'category_id' => $pastries->id,
                'description' => 'مافین تازه با بلوبری طبیعی و روکش کrumble. مناسب برای صبحانه.',
                'image' => 'https://images.unsplash.com/photo-1607920591413-4ec007e70023?w=400&h=300&fit=crop',
                'rating' => 4.6,
                'inventory' => 40,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'شیرینی دارچینی',
                'slug' => 'cinnamon-roll',
                'price' => 140000,
                'category_id' => $pastries->id,
                'description' => 'شیرینی دارچینی پیچیده با روکش خامه‌ای. عطر دارچین و شکر قهوه‌ای.',
                'image' => 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?w=400&h=300&fit=crop',
                'rating' => 4.7,
                'inventory' => 35,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'title' => 'نون خامه‌ای',
                'slug' => 'cream-pastry',
                'price' => 110000,
                'category_id' => $pastries->id,
                'description' => 'نون خامه‌ای تازه با خامه وانیلی. سبک و لطیف و خوشمزه.',
                'image' => 'https://images.unsplash.com/photo-1517433670267-08bbd4be890f?w=400&h=300&fit=crop',
                'rating' => 4.5,
                'inventory' => 45,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'title' => 'بیگل کشمشی',
                'slug' => 'raisin-bagel',
                'price' => 100000,
                'category_id' => $pastries->id,
                'description' => 'بیگل تازه با کشمش و دارچین. مناسب برای صبحانه با پنیر خامه‌ای.',
                'image' => 'https://images.unsplash.com/photo-1585478259715-876acc5be8eb?w=400&h=300&fit=crop',
                'rating' => 4.4,
                'inventory' => 55,
                'is_active' => true,
                'sort_order' => 5,
            ],

            // Breakfast
            [
                'title' => 'املت',
                'slug' => 'omelette',
                'price' => 250000,
                'category_id' => $breakfast->id,
                'description' => 'املت تازه با پنیر و سبزیجات. صبحانه‌ای کامل و مقوی.',
                'image' => 'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&h=300&fit=crop',
                'rating' => 4.7,
                'inventory' => 60,
                'is_active' => true,
                'sort_order' => 1,
            ],
            [
                'title' => 'پنکیک',
                'slug' => 'pancakes',
                'price' => 220000,
                'category_id' => $breakfast->id,
                'description' => 'پنکیک‌های نرم و پuffy با عسل و میوه‌های تازه. صبحانه‌ای شیرین و لذیذ.',
                'image' => 'https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=400&h=300&fit=crop',
                'rating' => 4.8,
                'inventory' => 45,
                'is_active' => true,
                'sort_order' => 2,
            ],
            [
                'title' => 'توست آووکادو',
                'slug' => 'avocado-toast',
                'price' => 280000,
                'category_id' => $breakfast->id,
                'description' => 'توست سبوس‌دار با آووکادو کرمی، تخم مرغ و ادویه‌جات. صبحانه سالم و مدرن.',
                'image' => 'https://images.unsplash.com/photo-1541519227354-08fa5d50c44d?w=400&h=300&fit=crop',
                'rating' => 4.6,
                'inventory' => 40,
                'is_active' => true,
                'sort_order' => 3,
            ],
            [
                'title' => 'سالاد فصل',
                'slug' => 'seasonal-salad',
                'price' => 200000,
                'category_id' => $breakfast->id,
                'description' => 'سالاد تازه فصل با سبزیجات ارگانیک و سس سزار. سبک و سالم.',
                'image' => 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&h=300&fit=crop',
                'rating' => 4.4,
                'inventory' => 50,
                'is_active' => true,
                'sort_order' => 4,
            ],
            [
                'title' => ' تست فرنچ',
                'slug' => 'french-toast',
                'price' => 230000,
                'category_id' => $breakfast->id,
                'description' => 'فرنچ تست با نان بریوش، تخم مرغ و دارچین. با عسل و میوه تازه سرو می‌شود.',
                'image' => 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=400&h=300&fit=crop',
                'rating' => 4.7,
                'inventory' => 35,
                'is_active' => true,
                'sort_order' => 5,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
